



POST https://apimafy.zeabur.app/api/facturaServicio

{
    "fecha": "2024-10-23",
    "cliente": "Ken",
    "servicios": [
        {
            "nombre": "Servicio 3",
            "descripcion": " Descripcion Genericas",
            "precio": 400,
            "cantidad": 1,
            "subtotal": "400.00"
        },
        {
            "nombre": "Servicio 2",
            "descripcion": " Descripcion Generica",
            "precio": 200,
            "cantidad": 1,
            "subtotal": "200.00"
        }
    ],
    "totalFactura": "600.00"
}



GET http://localhost:4000/api/FacturaServicio/reporte?startDate=2024-01-01&endDate=2024-10-22


POST  http://localhost:4000/api/auth/signin/?email=ken@gmail.com&password=1234

Content-Type: application/json

{
  "id_ventas": "659e144b26319c67332552fb",
  "articulos": [
    {
      "id_articulo": "659af68647b7d367ebc29354",
      "id_categoria": "6584fdd7331de1c471259dc1",
      "id_marca": "6566b1ff1693e94218aabf6e",
      "id_color": "6566b0ad1693e94218aabf51",
      "id_estilo": "6584658fef6c4c4663141a25",
      "id_material": "656156daf9c6ffbe9552ecf2",
      "id_talla": "6585dce4f8cb50dfa8178bb1",
      "id_diseño": "65387375e2fbfdbd8119fe5c",
      "id_promocion": "656406ab15f89660d2673fb4",
      "cantidad": 3,
      "precio": 25.99,
      "subtotal": 77.97,
      "descuento": 5
    }
  ],
  "total": 72.97
}

